/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as CabsRouteImport } from './routes/cabs'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoLoginRouteImport } from './routes/demo-login'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as ItinerariesRouteImport } from './routes/itineraries'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as PermitsRouteImport } from './routes/permits'
import { Route as StaysRouteImport } from './routes/stays'
import { Route as TrainsRouteImport } from './routes/trains'
import { Route as CreatorHandleRouteImport } from './routes/creator.$handle'
import { Route as CreatorsHandleRouteImport } from './routes/creators.$handle'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardCreatorRouteImport } from './routes/dashboard.creator'
import { Route as DashboardHostRouteImport } from './routes/dashboard.host'
import { Route as DashboardPlannerRouteImport } from './routes/dashboard.planner'
import { Route as DashboardTravelerRouteImport } from './routes/dashboard.traveler'
import { Route as ExploreSlugRouteImport } from './routes/explore.$slug'
import { Route as HostSlugRouteImport } from './routes/host.$slug'
import { Route as HostsIdRouteImport } from './routes/hosts.$id'
import { Route as InviteIndexRouteImport } from './routes/invite.index'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as ItinerariesCodeRouteImport } from './routes/itineraries.$code'
import { Route as ItineraryCodeRouteImport } from './routes/itinerary.$code'
import { Route as PackagesIdRouteImport } from './routes/packages.$id'
import { Route as PlannerSubdomainRouteImport } from './routes/planner.$subdomain'
import { Route as StaysIdRouteImport } from './routes/stays.$id'
import { Route as CreatorHandlePlanIdRouteImport } from './routes/creator.$handle.$planId'
import { Route as TripIdInviteRouteImport } from './routes/trip.$id.invite'
import { Route as TripIdSosRouteImport } from './routes/trip.$id.sos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const CabsRoute = CabsRouteImport.update({
  id: '/cabs',
  path: '/cabs',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLoginRoute = DemoLoginRouteImport.update({
  id: '/demo-login',
  path: '/demo-login',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesRoute = ItinerariesRouteImport.update({
  id: '/itineraries',
  path: '/itineraries',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PermitsRoute = PermitsRouteImport.update({
  id: '/permits',
  path: '/permits',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysRoute = StaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainsRoute = TrainsRouteImport.update({
  id: '/trains',
  path: '/trains',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorHandleRoute = CreatorHandleRouteImport.update({
  id: '/creator/$handle',
  path: '/creator/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsHandleRoute = CreatorsHandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => CreatorsRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreatorRoute = DashboardCreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHostRoute = DashboardHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlannerRoute = DashboardPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTravelerRoute = DashboardTravelerRouteImport.update({
  id: '/traveler',
  path: '/traveler',
  getParentRoute: () => DashboardRoute,
} as any)
const ExploreSlugRoute = ExploreSlugRouteImport.update({
  id: '/explore/$slug',
  path: '/explore/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSlugRoute = HostSlugRouteImport.update({
  id: '/host/$slug',
  path: '/host/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsIdRoute = HostsIdRouteImport.update({
  id: '/hosts/$id',
  path: '/hosts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteIndexRoute = InviteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InviteRoute,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => InviteRoute,
} as any)
const ItinerariesCodeRoute = ItinerariesCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => ItinerariesRoute,
} as any)
const ItineraryCodeRoute = ItineraryCodeRouteImport.update({
  id: '/itinerary/$code',
  path: '/itinerary/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIdRoute = PackagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PackagesRoute,
} as any)
const PlannerSubdomainRoute = PlannerSubdomainRouteImport.update({
  id: '/planner/$subdomain',
  path: '/planner/$subdomain',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysIdRoute = StaysIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaysRoute,
} as any)
const CreatorHandlePlanIdRoute = CreatorHandlePlanIdRouteImport.update({
  id: '/$planId',
  path: '/$planId',
  getParentRoute: () => CreatorHandleRoute,
} as any)
const TripIdInviteRoute = TripIdInviteRouteImport.update({
  id: '/trip/$id/invite',
  path: '/trip/$id/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const TripIdSosRoute = TripIdSosRouteImport.update({
  id: '/trip/$id/sos',
  path: '/trip/$id/sos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/builder': typeof BuilderRoute
  '/cabs': typeof CabsRoute
  '/creators': typeof CreatorsRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo-login': typeof DemoLoginRoute
  '/flights': typeof FlightsRoute
  '/invite': typeof InviteRouteWithChildren
  '/itineraries': typeof ItinerariesRouteWithChildren
  '/offers': typeof OffersRoute
  '/packages': typeof PackagesRouteWithChildren
  '/permits': typeof PermitsRoute
  '/stays': typeof StaysRouteWithChildren
  '/trains': typeof TrainsRoute
  '/creator/$handle': typeof CreatorHandleRouteWithChildren
  '/creators/$handle': typeof CreatorsHandleRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/creator': typeof DashboardCreatorRoute
  '/dashboard/host': typeof DashboardHostRoute
  '/dashboard/planner': typeof DashboardPlannerRoute
  '/dashboard/traveler': typeof DashboardTravelerRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/host/$slug': typeof HostSlugRoute
  '/hosts/$id': typeof HostsIdRoute
  '/invite/$code': typeof InviteCodeRoute
  '/itineraries/$code': typeof ItinerariesCodeRoute
  '/itinerary/$code': typeof ItineraryCodeRoute
  '/packages/$id': typeof PackagesIdRoute
  '/planner/$subdomain': typeof PlannerSubdomainRoute
  '/stays/$id': typeof StaysIdRoute
  '/invite/': typeof InviteIndexRoute
  '/creator/$handle/$planId': typeof CreatorHandlePlanIdRoute
  '/trip/$id/invite': typeof TripIdInviteRoute
  '/trip/$id/sos': typeof TripIdSosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/builder': typeof BuilderRoute
  '/cabs': typeof CabsRoute
  '/creators': typeof CreatorsRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo-login': typeof DemoLoginRoute
  '/flights': typeof FlightsRoute
  '/itineraries': typeof ItinerariesRouteWithChildren
  '/offers': typeof OffersRoute
  '/packages': typeof PackagesRouteWithChildren
  '/permits': typeof PermitsRoute
  '/stays': typeof StaysRouteWithChildren
  '/trains': typeof TrainsRoute
  '/creator/$handle': typeof CreatorHandleRouteWithChildren
  '/creators/$handle': typeof CreatorsHandleRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/creator': typeof DashboardCreatorRoute
  '/dashboard/host': typeof DashboardHostRoute
  '/dashboard/planner': typeof DashboardPlannerRoute
  '/dashboard/traveler': typeof DashboardTravelerRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/host/$slug': typeof HostSlugRoute
  '/hosts/$id': typeof HostsIdRoute
  '/invite/$code': typeof InviteCodeRoute
  '/itineraries/$code': typeof ItinerariesCodeRoute
  '/itinerary/$code': typeof ItineraryCodeRoute
  '/packages/$id': typeof PackagesIdRoute
  '/planner/$subdomain': typeof PlannerSubdomainRoute
  '/stays/$id': typeof StaysIdRoute
  '/invite': typeof InviteIndexRoute
  '/creator/$handle/$planId': typeof CreatorHandlePlanIdRoute
  '/trip/$id/invite': typeof TripIdInviteRoute
  '/trip/$id/sos': typeof TripIdSosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/builder': typeof BuilderRoute
  '/cabs': typeof CabsRoute
  '/creators': typeof CreatorsRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo-login': typeof DemoLoginRoute
  '/flights': typeof FlightsRoute
  '/invite': typeof InviteRouteWithChildren
  '/itineraries': typeof ItinerariesRouteWithChildren
  '/offers': typeof OffersRoute
  '/packages': typeof PackagesRouteWithChildren
  '/permits': typeof PermitsRoute
  '/stays': typeof StaysRouteWithChildren
  '/trains': typeof TrainsRoute
  '/creator/$handle': typeof CreatorHandleRouteWithChildren
  '/creators/$handle': typeof CreatorsHandleRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/creator': typeof DashboardCreatorRoute
  '/dashboard/host': typeof DashboardHostRoute
  '/dashboard/planner': typeof DashboardPlannerRoute
  '/dashboard/traveler': typeof DashboardTravelerRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/host/$slug': typeof HostSlugRoute
  '/hosts/$id': typeof HostsIdRoute
  '/invite/$code': typeof InviteCodeRoute
  '/itineraries/$code': typeof ItinerariesCodeRoute
  '/itinerary/$code': typeof ItineraryCodeRoute
  '/packages/$id': typeof PackagesIdRoute
  '/planner/$subdomain': typeof PlannerSubdomainRoute
  '/stays/$id': typeof StaysIdRoute
  '/invite/': typeof InviteIndexRoute
  '/creator/$handle/$planId': typeof CreatorHandlePlanIdRoute
  '/trip/$id/invite': typeof TripIdInviteRoute
  '/trip/$id/sos': typeof TripIdSosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/builder'
    | '/cabs'
    | '/creators'
    | '/dashboard'
    | '/demo-login'
    | '/flights'
    | '/invite'
    | '/itineraries'
    | '/offers'
    | '/packages'
    | '/permits'
    | '/stays'
    | '/trains'
    | '/creator/$handle'
    | '/creators/$handle'
    | '/dashboard/admin'
    | '/dashboard/creator'
    | '/dashboard/host'
    | '/dashboard/planner'
    | '/dashboard/traveler'
    | '/explore/$slug'
    | '/host/$slug'
    | '/hosts/$id'
    | '/invite/$code'
    | '/itineraries/$code'
    | '/itinerary/$code'
    | '/packages/$id'
    | '/planner/$subdomain'
    | '/stays/$id'
    | '/invite/'
    | '/creator/$handle/$planId'
    | '/trip/$id/invite'
    | '/trip/$id/sos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/builder'
    | '/cabs'
    | '/creators'
    | '/dashboard'
    | '/demo-login'
    | '/flights'
    | '/itineraries'
    | '/offers'
    | '/packages'
    | '/permits'
    | '/stays'
    | '/trains'
    | '/creator/$handle'
    | '/creators/$handle'
    | '/dashboard/admin'
    | '/dashboard/creator'
    | '/dashboard/host'
    | '/dashboard/planner'
    | '/dashboard/traveler'
    | '/explore/$slug'
    | '/host/$slug'
    | '/hosts/$id'
    | '/invite/$code'
    | '/itineraries/$code'
    | '/itinerary/$code'
    | '/packages/$id'
    | '/planner/$subdomain'
    | '/stays/$id'
    | '/invite'
    | '/creator/$handle/$planId'
    | '/trip/$id/invite'
    | '/trip/$id/sos'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/builder'
    | '/cabs'
    | '/creators'
    | '/dashboard'
    | '/demo-login'
    | '/flights'
    | '/invite'
    | '/itineraries'
    | '/offers'
    | '/packages'
    | '/permits'
    | '/stays'
    | '/trains'
    | '/creator/$handle'
    | '/creators/$handle'
    | '/dashboard/admin'
    | '/dashboard/creator'
    | '/dashboard/host'
    | '/dashboard/planner'
    | '/dashboard/traveler'
    | '/explore/$slug'
    | '/host/$slug'
    | '/hosts/$id'
    | '/invite/$code'
    | '/itineraries/$code'
    | '/itinerary/$code'
    | '/packages/$id'
    | '/planner/$subdomain'
    | '/stays/$id'
    | '/invite/'
    | '/creator/$handle/$planId'
    | '/trip/$id/invite'
    | '/trip/$id/sos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BuilderRoute: typeof BuilderRoute
  CabsRoute: typeof CabsRoute
  CreatorsRoute: typeof CreatorsRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoLoginRoute: typeof DemoLoginRoute
  FlightsRoute: typeof FlightsRoute
  InviteRoute: typeof InviteRouteWithChildren
  ItinerariesRoute: typeof ItinerariesRouteWithChildren
  OffersRoute: typeof OffersRoute
  PackagesRoute: typeof PackagesRouteWithChildren
  PermitsRoute: typeof PermitsRoute
  StaysRoute: typeof StaysRouteWithChildren
  TrainsRoute: typeof TrainsRoute
  CreatorHandleRoute: typeof CreatorHandleRouteWithChildren
  ExploreSlugRoute: typeof ExploreSlugRoute
  HostSlugRoute: typeof HostSlugRoute
  HostsIdRoute: typeof HostsIdRoute
  ItineraryCodeRoute: typeof ItineraryCodeRoute
  PlannerSubdomainRoute: typeof PlannerSubdomainRoute
  TripIdInviteRoute: typeof TripIdInviteRoute
  TripIdSosRoute: typeof TripIdSosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabs': {
      id: '/cabs'
      path: '/cabs'
      fullPath: '/cabs'
      preLoaderRoute: typeof CabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-login': {
      id: '/demo-login'
      path: '/demo-login'
      fullPath: '/demo-login'
      preLoaderRoute: typeof DemoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries': {
      id: '/itineraries'
      path: '/itineraries'
      fullPath: '/itineraries'
      preLoaderRoute: typeof ItinerariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permits': {
      id: '/permits'
      path: '/permits'
      fullPath: '/permits'
      preLoaderRoute: typeof PermitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays': {
      id: '/stays'
      path: '/stays'
      fullPath: '/stays'
      preLoaderRoute: typeof StaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trains': {
      id: '/trains'
      path: '/trains'
      fullPath: '/trains'
      preLoaderRoute: typeof TrainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/$handle': {
      id: '/creator/$handle'
      path: '/creator/$handle'
      fullPath: '/creator/$handle'
      preLoaderRoute: typeof CreatorHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/$handle': {
      id: '/creators/$handle'
      path: '/$handle'
      fullPath: '/creators/$handle'
      preLoaderRoute: typeof CreatorsHandleRouteImport
      parentRoute: typeof CreatorsRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/creator': {
      id: '/dashboard/creator'
      path: '/creator'
      fullPath: '/dashboard/creator'
      preLoaderRoute: typeof DashboardCreatorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/host': {
      id: '/dashboard/host'
      path: '/host'
      fullPath: '/dashboard/host'
      preLoaderRoute: typeof DashboardHostRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/planner': {
      id: '/dashboard/planner'
      path: '/planner'
      fullPath: '/dashboard/planner'
      preLoaderRoute: typeof DashboardPlannerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/traveler': {
      id: '/dashboard/traveler'
      path: '/traveler'
      fullPath: '/dashboard/traveler'
      preLoaderRoute: typeof DashboardTravelerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/explore/$slug': {
      id: '/explore/$slug'
      path: '/explore/$slug'
      fullPath: '/explore/$slug'
      preLoaderRoute: typeof ExploreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug': {
      id: '/host/$slug'
      path: '/host/$slug'
      fullPath: '/host/$slug'
      preLoaderRoute: typeof HostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$id': {
      id: '/hosts/$id'
      path: '/hosts/$id'
      fullPath: '/hosts/$id'
      preLoaderRoute: typeof HostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/': {
      id: '/invite/'
      path: '/'
      fullPath: '/invite/'
      preLoaderRoute: typeof InviteIndexRouteImport
      parentRoute: typeof InviteRoute
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof InviteRoute
    }
    '/itineraries/$code': {
      id: '/itineraries/$code'
      path: '/$code'
      fullPath: '/itineraries/$code'
      preLoaderRoute: typeof ItinerariesCodeRouteImport
      parentRoute: typeof ItinerariesRoute
    }
    '/itinerary/$code': {
      id: '/itinerary/$code'
      path: '/itinerary/$code'
      fullPath: '/itinerary/$code'
      preLoaderRoute: typeof ItineraryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$id': {
      id: '/packages/$id'
      path: '/$id'
      fullPath: '/packages/$id'
      preLoaderRoute: typeof PackagesIdRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/planner/$subdomain': {
      id: '/planner/$subdomain'
      path: '/planner/$subdomain'
      fullPath: '/planner/$subdomain'
      preLoaderRoute: typeof PlannerSubdomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays/$id': {
      id: '/stays/$id'
      path: '/$id'
      fullPath: '/stays/$id'
      preLoaderRoute: typeof StaysIdRouteImport
      parentRoute: typeof StaysRoute
    }
    '/creator/$handle/$planId': {
      id: '/creator/$handle/$planId'
      path: '/$planId'
      fullPath: '/creator/$handle/$planId'
      preLoaderRoute: typeof CreatorHandlePlanIdRouteImport
      parentRoute: typeof CreatorHandleRoute
    }
    '/trip/$id/invite': {
      id: '/trip/$id/invite'
      path: '/trip/$id/invite'
      fullPath: '/trip/$id/invite'
      preLoaderRoute: typeof TripIdInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$id/sos': {
      id: '/trip/$id/sos'
      path: '/trip/$id/sos'
      fullPath: '/trip/$id/sos'
      preLoaderRoute: typeof TripIdSosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CreatorsRouteChildren {
  CreatorsHandleRoute: typeof CreatorsHandleRoute
}

const CreatorsRouteChildren: CreatorsRouteChildren = {
  CreatorsHandleRoute: CreatorsHandleRoute,
}

const CreatorsRouteWithChildren = CreatorsRoute._addFileChildren(
  CreatorsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardCreatorRoute: typeof DashboardCreatorRoute
  DashboardHostRoute: typeof DashboardHostRoute
  DashboardPlannerRoute: typeof DashboardPlannerRoute
  DashboardTravelerRoute: typeof DashboardTravelerRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardCreatorRoute: DashboardCreatorRoute,
  DashboardHostRoute: DashboardHostRoute,
  DashboardPlannerRoute: DashboardPlannerRoute,
  DashboardTravelerRoute: DashboardTravelerRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface InviteRouteChildren {
  InviteCodeRoute: typeof InviteCodeRoute
  InviteIndexRoute: typeof InviteIndexRoute
}

const InviteRouteChildren: InviteRouteChildren = {
  InviteCodeRoute: InviteCodeRoute,
  InviteIndexRoute: InviteIndexRoute,
}

const InviteRouteWithChildren =
  InviteRoute._addFileChildren(InviteRouteChildren)

interface ItinerariesRouteChildren {
  ItinerariesCodeRoute: typeof ItinerariesCodeRoute
}

const ItinerariesRouteChildren: ItinerariesRouteChildren = {
  ItinerariesCodeRoute: ItinerariesCodeRoute,
}

const ItinerariesRouteWithChildren = ItinerariesRoute._addFileChildren(
  ItinerariesRouteChildren,
)

interface PackagesRouteChildren {
  PackagesIdRoute: typeof PackagesIdRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesIdRoute: PackagesIdRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

interface StaysRouteChildren {
  StaysIdRoute: typeof StaysIdRoute
}

const StaysRouteChildren: StaysRouteChildren = {
  StaysIdRoute: StaysIdRoute,
}

const StaysRouteWithChildren = StaysRoute._addFileChildren(StaysRouteChildren)

interface CreatorHandleRouteChildren {
  CreatorHandlePlanIdRoute: typeof CreatorHandlePlanIdRoute
}

const CreatorHandleRouteChildren: CreatorHandleRouteChildren = {
  CreatorHandlePlanIdRoute: CreatorHandlePlanIdRoute,
}

const CreatorHandleRouteWithChildren = CreatorHandleRoute._addFileChildren(
  CreatorHandleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BuilderRoute: BuilderRoute,
  CabsRoute: CabsRoute,
  CreatorsRoute: CreatorsRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DemoLoginRoute: DemoLoginRoute,
  FlightsRoute: FlightsRoute,
  InviteRoute: InviteRouteWithChildren,
  ItinerariesRoute: ItinerariesRouteWithChildren,
  OffersRoute: OffersRoute,
  PackagesRoute: PackagesRouteWithChildren,
  PermitsRoute: PermitsRoute,
  StaysRoute: StaysRouteWithChildren,
  TrainsRoute: TrainsRoute,
  CreatorHandleRoute: CreatorHandleRouteWithChildren,
  ExploreSlugRoute: ExploreSlugRoute,
  HostSlugRoute: HostSlugRoute,
  HostsIdRoute: HostsIdRoute,
  ItineraryCodeRoute: ItineraryCodeRoute,
  PlannerSubdomainRoute: PlannerSubdomainRoute,
  TripIdInviteRoute: TripIdInviteRoute,
  TripIdSosRoute: TripIdSosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
